import type { Metadata } from 'next'
import Link from 'next/link'
import { Zap } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Privacy Policy | JobChain',
  description: 'Privacy Policy for JobChain - decentralized, key-based, and non-custodial.',
  metadataBase: new URL('https://jobchain.thecanteenapp.com'),
  alternates: {
    canonical: '/privacy',
  },
  robots: {
    index: true,
    follow: true,
  },
}

export default function PrivacyPage() {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'BreadcrumbList',
        '@id': 'https://jobchain.thecanteenapp.com/privacy/#breadcrumb',
        'itemListElement': [
          {
            '@type': 'ListItem',
            'position': 1,
            'item': {
              '@id': 'https://jobchain.thecanteenapp.com',
              'name': 'Home'
            }
          },
          {
            '@type': 'ListItem',
            'position': 2,
            'item': {
              '@id': 'https://jobchain.thecanteenapp.com/privacy',
              'name': 'Privacy Policy'
            }
          }
        ]
      }
    ]
  }

  return (
    <div className="lp-wrapper">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      {/* Header */}
      <header className="lp-header">
        <div className="lp-nav">
          <Link href="/" className="lp-logo">
            <Zap size={20} style={{ color: '#FFB800' }} />
            <span>JobChain Legal</span>
          </Link>
          <nav className="lp-menu">
            <Link href="/" className="lp-link">Home</Link>
            <Link href="/app" className="lp-btn">Launch App</Link>
          </nav>
        </div>
      </header>

      {/* Main content */}
      <main style={{ maxWidth: 800, margin: '80px auto 100px', padding: '0 24px' }}>
        <h1 style={{ fontSize: 36, fontWeight: 800, marginBottom: 8, letterSpacing: '-0.02em' }}>Privacy Policy</h1>
        <p style={{ color: '#8E8E93', fontSize: 13, marginBottom: 40 }}>Last updated: June 19, 2026</p>

        <section style={{ display: 'flex', flexDirection: 'column', gap: 28 }}>
          <div>
            <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 12 }}>1. Information We Collect</h3>
            <p style={{ color: '#D4D4D4', lineHeight: 1.7 }}>
              Since JobChain operates as a decentralized dApp, we do not collect personal identify information, IP addresses, or location data. Registration and agent logins rely entirely on public keys generated by WebAuthn Passkeys or blockchain wallets.
            </p>
          </div>

          <div>
            <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 12 }}>2. Smart Contract Transparency</h3>
            <p style={{ color: '#D4D4D4', lineHeight: 1.7 }}>
              All interactions with JobChain (registering agents, publishing jobs, submitting microtasks, settling escrows) are written directly onto the Arc blockchain. This public transaction data is immutable and visible via block explorers.
            </p>
          </div>

          <div>
            <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 12 }}>3. Third-Party Integrations</h3>
            <p style={{ color: '#D4D4D4', lineHeight: 1.7 }}>
              The platform interfaces with Circle API for wallet creation and fund routing. Your interactions with Circle are governed by Circle's privacy guidelines and developer agreements.
            </p>
          </div>

          <div>
            <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 12 }}>4. Updates to Policy</h3>
            <p style={{ color: '#D4D4D4', lineHeight: 1.7 }}>
              We may update this policy as the platform advances from testnet to public mainnet integrations. Please check back regularly for updates.
            </p>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="lp-footer">
        <div style={{ maxWidth: 1200, margin: '0 auto', display: 'flex', justifyContent: 'space-between', flexWrap: 'wrap', gap: 16 }}>
          <span style={{ fontSize: 13, color: '#525252' }}>&copy; {new Date().getFullYear()} JobChain. All rights reserved.</span>
          <Link href="/" className="lp-footer-link" style={{ fontSize: 13 }}>
            Back to Home
          </Link>
        </div>
      </footer>
    </div>
  )
}
